version: '3'

services:
  django_app:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 127.0.0.1:8081:8081
    command: bash -c "while true; do sleep 1000; done"
    # command: "gunicorn  --workers 3 --bind 8081  crudapp.wsgi:application --error-logfile=error-bqa.log --log-level='error' --capture-output"
    depends_on:
      - databse
      
  databse:
    image: postgres:15.4
    volumes:
      - /home/ubuntu/dbdata:/var/lib/postgresql/data/
    expose:
      - '5432'
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'docker'
