# Generated by Django 2.2 on 2019-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Crud',
                'verbose_name_plural': 'Cruds',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
