# Generated by Django 2.2 on 2019-04-20 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crud',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='type here'),
        ),
    ]
