name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - run: docker-compose up -d
